# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: curl -fsSL https://install.julialang.org | sh
    init: juliaup add 1.8.5~x86
    command: juliaup self update

# Ports to expose on workspace startup
# ports:
#   - port: 3000
#     onOpen: open-preview
#     name: Website
#     description: Website Preview